print("Marc Jomari M. Malacas")
print("Mercado, Boac, Marinduque")
print("August 17, 2003")
print("College of Information and Computing Sciences")
print("Bachelor of Science in Information Technology")
print("2nd Year - B")
print("Playing Video Games")
print("Reading Manga, Manhwa, Manhua")
print("Learning programming or coding")
print("Listening to music")
print("Playing badminton")